name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore samples/api-identity/Blazor-Api-Identity
    - name: Build
      run: dotnet build samples/api-identity/Blazor-Api-Identity --configuration Release --no-restore
    - name: Test
      run: dotnet test samples/api-identity/Blazor-Api-Identity --no-restore --verbosity normal
